### ISSUE TITLE
PIS flow for International Payments results in an error on /authorise screen

### ISSUE THREAD

**Issue by BohoCode** [OpenBankingToolkit/openbanking-toolkit#13]
**ZD:** 55780
**Version:** INXS-RC2

When trying to gain PSU consent to make an international payment (via https://bank.<domain>/consent?consent_request=<jwt>) the following stack trace was seen when the bank UI tries to obtain the consent from the RCS;

```
Caused by: java.lang.NullPointerException: null
	at com.forgerock.openbanking.aspsp.rs.rcs.api.rcs.details.RCSInternationalPaymentDetailsApi.consentDetails(RCSInternationalPaymentDetailsApi.java:89)
	at com.forgerock.openbanking.aspsp.rs.rcs.services.IntentTypeService.consentDetails(IntentTypeService.java:139)
	at com.forgerock.openbanking.aspsp.rs.rcs.api.rcs.RCSDetailsGatewayApiController.details(RCSDetailsGatewayApiController.java:92)
	at jdk.internal.reflect.GeneratedMethodAccessor266.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	... 106 common frames omitted
```

**Comment by BohoCode** [comment]
The code for INXS-RC is not even in the OpenBankingToolkit. 

Please see internal pre toolkit code - tag 3.1.2-inxs-rc2 in ob-reference-implemenation.

**Comment by BohoCode** [comment]
The issue is still in our current code base however. The problem is with this [line](https://github.com/OpenBankingToolkit/openbanking-aspsp/blob/61d0a2236bb1e1a7ee6068d21dcc593ea977d671/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-rcs/forgerock-openbanking-uk-aspsp-rs-rcs-server/src/main/java/com/forgerock/openbanking/aspsp/rs/rcs/api/rcs/details/RCSInternationalPaymentDetailsApi.java#L101) where `payment.getCalculatedExchangeRate()` can return a null. When this occurs line 105 is destined for a Null Pointer Exception. 

In the FRInternationalConsent2 object that is referenced in the failing request it can be seen that the exchangeRateInformation is null. 

According to the spec this should be optional (0..1) relationship.
https://openbankinguk.github.io/read-write-api-site3/v3.1.6/resources-and-data-models/pisp/international-payment-consents.html#post-international-payment-consents
